// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example for Android:
/// ```dart
/// apiKey: "YOUR-API-KEY",
/// appId: "YOUR-APP-ID",
/// messagingSenderId: "YOUR-MESSAGING-SENDER-ID",
/// projectId: "YOUR-PROJECT-ID",
/// storageBucket: "YOUR-STORAGE-BUCKET",
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASeX8Xo3lzH3m1D3Xw3ZigOHbRF4Tqmqg',
    appId: '1:1054706070242:web:c65c7790f4728a2b13e4bb',
    messagingSenderId: '1054706070242',
    projectId: 'serverpod-hackathon',
    authDomain: 'serverpod-hackathon.firebaseapp.com',
    storageBucket: 'serverpod-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdIlI-gKzhrCvnwfnU38KV1N_zLEY_k_M',
    appId: '1:1054706070242:android:91327fdac08319f313e4bb',
    messagingSenderId: '1054706070242',
    projectId: 'serverpod-hackathon',
    storageBucket: 'serverpod-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6zVfNc27VdeFaxVw8YfvaUDi7JSWHlaA',
    appId: '1:1054706070242:ios:c719c6922d5305d113e4bb',
    messagingSenderId: '1054706070242',
    projectId: 'serverpod-hackathon',
    storageBucket: 'serverpod-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.serverpodHackathonFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6zVfNc27VdeFaxVw8YfvaUDi7JSWHlaA',
    appId: '1:1054706070242:ios:c719c6922d5305d113e4bb',
    messagingSenderId: '1054706070242',
    projectId: 'serverpod-hackathon',
    storageBucket: 'serverpod-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.serverpodHackathonFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}